import { Inter } from 'next/font/google'
import './globals.css'
import '../public/css/style.css'
import '../public/css/slick.min.css'
import '../public/css/magnific-popup.min.css'
import '../public/css/fontawesome.min.css'
import '../public/css/bootstrap.min.css'
import MainHeader from './components/MainHeader'
import MainFooter from './components/MainFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Plumner - Plumbing Service Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader/>
        {children}
        <MainFooter/>
      </body>
    </html>
  )
}
