import { Inter } from 'next/font/google'




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Plumner - Plumbing Service Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="css/bootstrap.min.css"/>
        <link rel="stylesheet" href="css/fontawesome.min.css"/>
        <link rel="stylesheet" href="css/magnific-popup.min.css"/>
        <link rel="stylesheet" href="css/slick.min.css"/>
        <link rel="stylesheet" href="css/style.css"/>
      </head>
      
      <body>
        {children}
      </body>
    </html>
  )
}
